---
# tasks file for jenkins
- name: Installing boto.
  pip:
    name: boto

- name: Launch docker master EC2 instance
  ec2:
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    key_name: "{{ keypair }}"
    group_id: "{{ security_group }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    user_data: |
      #!/bin/bash
      yum install wget vim -y
      yum install epel-release -y
      yum install ansible git bcrypt -y
      # install roles
      ansible-galaxy install geerlingguy.jenkins
      ansible-galaxy install geerlingguy.puppet
      ansible-galaxy install hemanth22.createuser
      # download and create passwd for root
      wget -O rootuser.yaml https://gist.github.com/hemanth22/c0cdbbbd837b562628cc6796f831da16/raw
      ansible-playbook rootuser.yaml
      # download and restart SSHD
      wget -O sshd.yaml https://gist.github.com/hemanth22/55af63fab208201bfffd4db49827d8ad/raw
      ansible-playbook sshd.yaml
      # download and install puppetconf
      wget -O puppetconf.yaml https://gist.githubusercontent.com/hemanth22/867610b7a9e50781181d89bca95b79ca/raw/d476d4ea3fb7ca3dbf8469a20e5c6e42e03a1ba4/puppetconf.yaml
      ansible-playbook puppetconf.yaml
      ansible-playbook /root/.ansible/roles/geerlingguy.puppet/molecule/default/playbook.yml
      # install docker
      wget -O- https://get.docker.com/ | sh
      systemctl status docker
      systemctl start docker
      systemctl enable docker
      systemctl status docker
      systemctl status -l docker
      yum install -y docker-compose
      #Granting access to centos
      usermod -a -G docker centos
      systemctl restart docker
      systemctl status -l docker
      #Activating butterfly web terminal
      docker pull georgeyord/butterfly-web-terminal
      docker run --env PASSWORD=passd -p 2233:2233 -d georgeyord/butterfly-web-terminal
    wait: true
    wait_timeout: 500
    instance_tags:
      Name: master
      Environment: Production
    region: "{{ region }}"
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: "{{ volume_size }}"
        delete_on_termination: true
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    assign_public_ip: true
  register: ec2

- name: Add new instance to host group
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: launched
  loop: "{{ ec2.instances }}"

- name: Launch node docker EC2 instance
  ec2:
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    key_name: "{{ keypair }}"
    group_id: "{{ security_group }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    user_data: |
      #!/bin/bash
      yum install wget vim -y
      yum install epel-release -y
      yum install ansible git bcrypt -y
      # install roles
      ansible-galaxy install geerlingguy.jenkins
      ansible-galaxy install geerlingguy.puppet
      ansible-galaxy install hemanth22.createuser
      # download and create passwd for root
      wget -O rootuser.yaml https://gist.github.com/hemanth22/c0cdbbbd837b562628cc6796f831da16/raw
      ansible-playbook rootuser.yaml
      # download and restart SSHD
      wget -O sshd.yaml https://gist.github.com/hemanth22/55af63fab208201bfffd4db49827d8ad/raw
      ansible-playbook sshd.yaml
      # download and install puppetconf
      wget -O puppetconf.yaml https://gist.githubusercontent.com/hemanth22/867610b7a9e50781181d89bca95b79ca/raw/d476d4ea3fb7ca3dbf8469a20e5c6e42e03a1ba4/puppetconf.yaml
      ansible-playbook puppetconf.yaml
      ansible-playbook /root/.ansible/roles/geerlingguy.puppet/molecule/default/playbook.yml
      # install docker
      wget -O- https://get.docker.com/ | sh
      systemctl status docker
      systemctl start docker
      systemctl enable docker
      systemctl status docker
      systemctl status -l docker
      yum install -y docker-compose
      #Granting access to centos
      usermod -a -G docker centos
      systemctl restart docker
      systemctl status -l docker
      wget -O selenium.sh https://gist.github.com/hemanth22/d35284b0d203d3a99212bb38224e0ca0/raw
      chmod 777 selenium.sh
      ./selenium.sh
    wait: true
    wait_timeout: 500
    instance_tags:
      Name: node
      Environment: Development
    region: "{{ region }}"
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: "{{ volume_size }}"
        delete_on_termination: true
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    assign_public_ip: true
  register: ec2

- name: Add new instance to host group
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: launched
  loop: "{{ ec2.instances }}"
